services:
  filegator:
    image: filebrowser/filebrowser
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/filegator/filebrowser.db:/database/filebrowser.db
      - ${HOME}/storage:/data
    environment:
      - FB_PORT=80
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/data
    labels:
      caddy: filebrowser.${BASE_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  default:
    external:
      name: caddy
