services:
  memos:
    image: neosmemo/memos:0.22.4@sha256:b17a43b084327a8e37121fc3cce67a0a43b8a3ad75f9e9fa51c3f5b5ace290b4
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/memos:/var/opt/memos
    labels:
      caddy: memos.${BASE_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 5230}}"

networks:
  default:
    external:
      name: caddy
