services:
  server:
    image: linuxserver/jellyfin:10.9.9@sha256:88db4425a59157eba4b0fba8feb7df22a747a8134bb4d898070ef662f2c09b66
    restart: on-failure
    # TODO: verify if hostname is needed here
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/jellyfin/data/config:/config
      - ${HOME}/storage:/storage
    ports:
      # Service auto-discovery
      - 7359:7359/udp
    labels:
      caddy: jellyfin.${BASE_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8096}}"

networks:
  default:
    external:
      name: caddy
