services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    # caddy cannot run at user level since it binds to 80 & 443
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/caddy:/data
    restart: unless-stopped
    labels:
      caddy.email: ${ADMIN_EMAIL}

networks:
  caddy:
    external: true
